### ISSUE TITLE
Assertion violated in InnerModuleLinking

### ISSUE THREAD

**Issue by nicolo-ribaudo** [nicolo-ribaudo/modules-import-hooks-refactor#2]
https://nicolo-ribaudo.github.io/modules-import-hooks-refactor/#sec-moduledeclarationlinking

With these three files:
```js
// main
import "a";
import "b";
```
```js
// a
import("b");
```
```js
// b
```

When calling `main.Evaluate()`:
- The status of `main`, `a` and `b` transitions to `evaluating`
- `import("b")` synchronously calls `b.Link()`, but `b`'s status is `evaluating`

**Comment by guybedford** [comment]
The evaluating state is always supposed to synchronously transition - that is it should never be observable outside of any one top-level evaluation call.

**Comment by nicolo-ribaudo** [comment]
The bug with the current spec in this repo is that it calls `import("b")`->`b.Link()` _synchronously_ if `HostLoadImportedModule` returns synchronously, and at that time `"b"`'s status is `evaluating`. There hasn't been a promise tick yet since when `main.Evaluate()` was called.

I can fix this by always waiting a tick before `.Link()` even if the module was already loaded.

**Comment by guybedford** [comment]
That sounds correct to me.
